In [13]:
# import the libraries
import numpy as np
import pandas as pd
import statistics

In [18]:
data = [12, 15, 36, 41, 18, 27, 41, 37, 41, 25, 95, 10, 25, 124]
np_data = np.array(data)
print(np_data)

[ 12  15  36  41  18  27  41  37  41  25  95  10  25 124]


### Measure of Central Tendency

In [19]:
# First start with mean
np.mean(np_data)

39.07142857142857

In [20]:
# median
np.median(np_data)

31.5

In [21]:
# mode
statistics.mode(np_data)

41

## Percentiles

In [30]:
np.percentile(np_data, 25)

19.75

In [31]:
# We also find multiple percentiles in one code
np.percentile(np_data, [25, 50, 75])

array([19.75, 31.5 , 41.  ])

## Measure of Dispersion

In [32]:
# Variance
np.var(np_data)

964.9234693877552

In [33]:
# standard deviation
np.std(np_data)

31.06321730580648

In [34]:
# Interquatile range
# IQR = Q3 - Q1
IQR = np.percentile(np_data, 75) - np.percentile(np_data, 25)
print(IQR)

21.25


In [36]:
np_data_1 = np.array([15, 25, 36, 21, 65, 74, 98, 88, 10, 54])
np_data_2 = np.array([45, 75, 46, 24, 19, 88, 110, 74, 94, 16])
np.corrcoef(np_data_1, np_data_2)

array([[1.        , 0.29507011],
       [0.29507011, 1.        ]])